#!/usr/bin/env node

var fs = require('fs');

var config,
    configFile,
    nonInteractive;

nonInteractive = false;
process.argv.forEach(function (arg) {
  if (arg == '--non-interactive') {
    nonInteractive = true;
  }
});


// work from same directory as this script
process.chdir(__dirname);


config = {};
configFile = '../conf/config.json';


// TODO: make this more interactive
config.MOUNT_PATH = '/ws/hydra';
config.PORT = 8000;


// write configuration
fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
